# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('R', 'Rock'), ('S', 'Scissors'), ('P', 'Papper')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='Bet1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Items'),
        ),
        migrations.AddField(
            model_name='games',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.User'),
        ),
    ]
