# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 11, 49, 482304))),
                ('user1login', models.CharField(default='bot', max_length=16)),
                ('user2login', models.CharField(default='bot', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('R', 'Rock'), ('S', 'Scissors'), ('P', 'Paper')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wins', models.CharField(default=0, max_length=16)),
                ('Loses', models.CharField(default=0, max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='bet1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bet1', to='game.Item'),
        ),
        migrations.AddField(
            model_name='game',
            name='bet2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bet2', to='game.Item'),
        ),
    ]
