# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('R', 'Rock'), ('S', 'Scissors'), ('P', 'Paper')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='Bet1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuserbet', to='game.Items'),
        ),
        migrations.AddField(
            model_name='games',
            name='Bet2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seconduserbet', to='game.Items'),
        ),
        migrations.AddField(
            model_name='games',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='User2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seconduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
