# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 14, 56, 441249)),
        ),
    ]
