# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Bet2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seconduserbet', to='Game.Items'),
        ),
        migrations.AddField(
            model_name='games',
            name='User2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seconduser', to='Game.User'),
        ),
        migrations.AlterField(
            model_name='games',
            name='Bet1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuserbet', to='Game.Items'),
        ),
        migrations.AlterField(
            model_name='games',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to='Game.User'),
        ),
    ]
