# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20170602_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='User2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seconduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
