# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170608_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Loses',
            new_name='loses',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Wins',
            new_name='wins',
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 19, 3, 627512)),
        ),
    ]
