# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170608_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='drows',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 19, 43, 398223)),
        ),
    ]
