# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170608_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 20, 44, 495895)),
        ),
        migrations.AlterField(
            model_name='player',
            name='drows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
