# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170608_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='login',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 23, 9, 463867)),
        ),
    ]
