# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170608_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joindate',
            field=models.DateField(default=datetime.date(2017, 6, 8)),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 26, 8, 241802)),
        ),
    ]
