# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170608_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 23, 33, 33, 133001)),
        ),
        migrations.AlterField(
            model_name='player',
            name='joindate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
