# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170608_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.CharField(default='drow', max_length=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 1, 39, 46, 12455)),
        ),
    ]
