# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170609_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 2, 15, 0, 934343)),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('1', 'Rock'), ('2', 'Scissors'), ('3', 'Paper')], max_length=1),
        ),
    ]
